# Generated by Django 5.0.2 on 2024-03-25 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
            migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('last_connected', models.DateField(blank=True, null=True)),
                ('commentaire', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='AdMPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'AdMPReport',
                'verbose_name_plural': 'AdMPReports',
            },
        ),
        migrations.CreateModel(
            name='ADStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('commentaire', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'ADStatus',
                'verbose_name_plural': 'ADStatus',
            },
        ),

        migrations.CreateModel(
            name='TemporaireDRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TemporaireDRH',
                'verbose_name_plural': 'TemporairesDRH',
            },
        ),
    ]
