# Generated by Django 5.0.2 on 2024-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='taritement',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
