# Generated by Django 5.0.2 on 2024-02-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='matricule',
        ),
    ]
