# Generated by Django 5.0.2 on 2024-03-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_taritement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='taritement',
            new_name='traitement',
        ),
    ]
