# Generated by Django 5.0.2 on 2024-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_record_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='statuts',
        ),
        migrations.AddField(
            model_name='record',
            name='group',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur'), ('guest', 'Invité')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('pending', 'En attente')], default='active', max_length=20),
        ),
    ]
