# Generated by Django 5.0.2 on 2024-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_record_statuts_record_group_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_connected',
            field=models.DateField(),
        ),
    ]
