# Generated by Django 5.0.2 on 2024-02-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_record_last_connected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='status',
            new_name='statuts',
        ),
    ]
