# Generated by Django 5.0.2 on 2024-04-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_extraction_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admpreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='admpreport',
            name='username',
        ),
        migrations.AddField(
            model_name='admpreport',
            name='account_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admpreport',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admpreport',
            name='email_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admpreport',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admpreport',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admpreport',
            name='initials',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admpreport',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admpreport',
            name='sam_account_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
