# Generated by Django 5.0.2 on 2024-02-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_status_record_statuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='group',
        ),
    ]
