# Generated by Django 5.0.2 on 2024-02-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_record_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='statuts',
            field=models.CharField(choices=[('A garder', 'A garder'), ('A supprimer', 'A supprimer'), ('En attente', 'En attente')], default='A garder', max_length=20),
        ),
    ]
