# Generated by Django 5.0.2 on 2024-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_record_statuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='statuts',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('pending', 'En attente')], default='active', max_length=20),
        ),
    ]
