# Generated by Django 5.0.2 on 2024-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_record_last_connected_alter_record_statuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='commentaire',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
