# Generated by Django 5.0.2 on 2024-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_record_options_alter_record_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='commentaire',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
