# Generated by Django 5.0.2 on 2024-03-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_connected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
