# Generated by Django 5.0.2 on 2024-03-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_record_last_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='statuts',
        ),
    ]
