# Generated by Django 5.0.2 on 2024-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_admpreport_adstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adstatus',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
