# Generated by Django 5.0.2 on 2024-03-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_adstatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adstatus',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='adstatus',
            name='last_name',
        ),
    ]
