# Generated by Django 5.0.2 on 2024-03-15 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_first_name_adstatus_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaireDRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TemporaireDRH',
                'verbose_name_plural': 'TemporairesDRH',
            },
        ),
    ]
