# Generated by Django 5.0.2 on 2024-03-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_temporairedrh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adstatus',
            name='status',
        ),
    ]
